### ISSUE TITLE
Problem with removing modules from `sys.modules`

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1024]
**Describe the bug**
I discovered a bug probably related to the approach of loading each component at a time + uploading/downloading `sys.modules` (not currently merged).

Example: `OEFHandler.handle` of `weather_client` skill:

```python
def handle(...):
    ...
    if oef_msg.performative is OefSearchMessage.Performative.SEARCH_RESULT:
        ....
```

Without the `_SysModules.load_dependencies` instructions, the condition is satisfied. But with them, even if the performative is `SEARCH_RESULT`, the condition fails. I suspect it is due to some weird corner case of Protobuf/Pickle deserialization plus the fact that the modules of the objects are downloaded from `sys.modules`. Basically, the enum object `oef_msg.performative` and `SEARCH_RESULT` become different objects. Related to #607 
**To Reproduce**

Uncomment the following lines:
- https://github.com/fetchai/agents-aea/blob/develop/aea/configurations/components.py#L140
- https://github.com/fetchai/agents-aea/blob/develop/aea/aea_builder.py#L406

Run the weather demo:
- run the weather station agent
- run the weather client agent

Then, check what happens at this line of the weather client handler:
https://github.com/fetchai/agents-aea/blob/develop/packages/fetchai/skills/weather_client/handlers.py#L319

this condition
`oef_msg.performative is OefSearchMessage.Performative.SEARCH_RESULT`

evaluates to `False`, although the performative is `SEARCH_RESULT`.

**Expected behavior**
The condition is satisfied.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: N/A
 - Version https://github.com/fetchai/agents-aea/commit/df2455b3d34cc3fab4ad7d29cd0afbabbeab5e71

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by marcofavorito** [comment]
The problem seems to be wider. Removing modules from `sys.modules` prevents some libraries to not work as expected. 

For instance, currently, the serializers use `pickle` to serialize some objects.
However, from pickle docs:
https://docs.python.org/3/library/pickle.html#comparison-with-marshal

> pickle can save and restore class instances transparently, however the class definition must be importable and live in the same module as when the object was stored.

I tried with an example, which to some extents reproduces what happens in the encode method of any serializer. The serializer uses pickle to encode data structures. However, if the class of the data structure is not importable, it cannot be pickled. Unfortunately, this is the case of the new import approach where we remove all modules whose import path starts with `pacakges.*`:

(example contains the definition of `class A: pass`)
```python
from example import A
import picklea = A()
pickle.dumps(a)  # OK
sys.modules.pop("example")
pickle.dumps(a)
```

The last `pickle.dumps` raises this:
```
Traceback (most recent call last):
  File "/home/marcofavorito/.virtualenvs/agents-aea/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-53c63b3d4c9a>", line 7, in <module>
    pickle.dumps(a)
_pickle.PicklingError: Can't pickle <class 'example.A'>: it's not the same object as example.A
```
