### ISSUE TITLE
registry_path configuration issues with aea install

### ISSUE THREAD

**Issue by eorituz** [fetchai/agents-aea#2442]
**Describe the bug**
When setting up a new agent `aea install` runs just fine. 
It creates an `aea-config.yaml` as expected. However, this config does not include a configuration for the `registry_path` (aea <= 0.11 did)
This leads to issues when trying to add connections later on, because the registry_path is neither specified nor does the default folder `packages` exist.:
```
(sensor_demo_aea) oliver@bbpc:~/Arbeit/aea/trade_aea/my_generic_seller$ aea add connection fetchai/p2p_libp2p:0.21.0
Adding connection 'fetchai/p2p_libp2p:0.21.0'...
Traceback (most recent call last):
  File "/home/oliver/.virtualenvs/sensor_demo_aea/bin/aea", line 8, in <module>
    sys.exit(cli())
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/aea/cli/add.py", line 68, in connection
    add_item(ctx, CONNECTION, connection_public_id)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/aea/cli/utils/decorators.py", line 218, in wrapper
    return func(context, *args, **kwargs)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/aea/cli/add.py", line 123, in add_item
    package_path = fetch_item_mixed(ctx, item_type, item_public_id, dest_path)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/aea/cli/add.py", line 221, in fetch_item_mixed
    ctx, item_type, item_public_id, dest_path
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/aea/cli/add.py", line 198, in find_item_locally_or_distributed
    source_path, _ = find_item_locally(ctx, item_type, item_public_id)
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/aea/cli/utils/package_utils.py", line 307, in find_item_locally
    ctx.registry_path, item_public_id.author, item_type_plural, item_name
  File "/home/oliver/.virtualenvs/sensor_demo_aea/lib/python3.7/site-packages/aea/cli/utils/context.py", line 77, in registry_path
    f"Registry path not provided and `{DEFAULT_REGISTRY_NAME}` not found in current ({self.cwd}) and parent directory."
ValueError: Registry path not provided and `packages` not found in current (.) and parent directory.
```

**To Reproduce**
1. Follow the trade demo: https://docs.fetch.ai/aea/generic-skills-step-by-step/#run-the-aeas

**Expected behavior**
I'd either expect that `aea install` creates a `/packages` folder in the workdir or specifies a `registry_path` in the created default `aea-config.yaml`

**Desktop (please complete the following information):**
```
(sensor_demo_aea) oliver@bbpc:~/Arbeit/aea/trade_aea/test_agent$ uname -a
Linux bbpc 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
(sensor_demo_aea) oliver@bbpc:~/Arbeit/aea/trade_aea/test_agent$ aea --version
aea, version 1.0.0
```

**Comment by DavidMinarsch** [comment]
Hi @eorituz , we intentionally removed this configuration from `aea-config.yaml` as it's not a per-project configuration, rather a per development setup configuration. Unfortunately, in the time left we did not manage to extend `aea init` to configure this. So at the moment, you need to either create the packages folder manually `mkdir packages` in the root directory (i.e. where you call `aea fetch` or `aea create`) or you need to use the flag `--remote` when using `aea fetch`/`aea add`.

**Comment by DavidMinarsch** [comment]
A third way is to directly pass the path to `packages` to the cli command as an optional argument following `aea`.

**Comment by DavidMinarsch** [comment]
So in the above example, you can do `aea add --remote connection fetchai/p2p_libp2p:0.21.0`

**Comment by eorituz** [comment]
Ok, thanks for the clarification. I assumed the registry path is a "per-project" configuration.

**Comment by DavidMinarsch** [comment]
> Ok, thanks for the clarification. I assumed the registry path is a "per-project" configuration.

The way to think about `packages` is like a simple registry but local with no support for multiple versions (each package can only be present in one version). But all local agent projects can fetch/add from it and push/publish to it when using flag `--local`.
